---
name: Build new AMP API Spec

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0/4 * * *"

env:
  AMP_URL: ${{ secrets.AMP_URL }}
  AMP_USERNAME: ${{ secrets.AMP_USERNAME }}
  AMP_PASSWORD: ${{ secrets.AMP_PASSWORD }}

jobs:
  update_spec:
    name: Update AMP API Spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run the bash script
        run: bash update_spec.sh

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: p0t4t0sandwich
          author_email: p0t4t0sandwich@gmail.com
          message: "Update to $AMP_VERSION"
