---
  name: Build new AMP API Spec
  
  on:
    push:
      branches:
        - main
    schedule:
      - cron: "0 0/4 * * *"

  jobs:
    update_spec:
      name: Update AMP API Spec
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Run the bash script
          id: generate-spec
          run: python3 generate_spec.py ${{ secrets.AMP_URL }} ${{ secrets.AMP_USERNAME }} ${{ secrets.AMP_PASSWORD }}

        - uses: EndBug/add-and-commit@v9
          with:
            message: "Update to v${{ steps.generate-spec.outputs.AMP_VERSION }}"
            push: origin HEAD:main
            add: '["APISpec.json", "friendlySpec.txt", "AMPVersion.txt"]'
