---
  name: Build new AMP API Spec
  
  on:
    push:
      branches:
        - main
    schedule:
      - cron: "0 0/4 * * *"

  jobs:
    update_spec:
      name: Update AMP API Spec
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        - name: Run the bash script
          id: generate-spec
          run: bash update_spec.sh ${{ secrets.AMP_URL }} ${{ secrets.AMP_USERNAME }} ${{ secrets.AMP_PASSWORD }}

        - uses: EndBug/add-and-commit@v9
          with:
            author_name: p0t4t0sandwich
            author_email: p0t4t0sandwich@gmail.com
            message: "Update to v${{ steps.generate-spec.outputs.AMP_VERSION }}"
            add: '["APISpec.json", "friendlySpec.txt"]'
